# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
field_selection:
  transaction_fields:
    - hash
networks:
  - id: 69
    start_block: 24412635
    rpc_config:
      url: https://minanet-fork-production.up.railway.app
    contracts:
      - name: Launchpad
        address:
          - 0x63e39e1b03a72B721D6398D67A646705B33979eD
        handler: src/EventHandlers.ts
        events:
          - event: TokenLaunched(address indexed token, address indexed creator, string name, string symbol)
      - name: Token
        handler: src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 value)
unordered_multichain_mode: true
preload_handlers: true
